# Global Settings
[global]
debug = true
interval = 300
daemon = false

# EVCC Settings
[evcc]
host = "evcc-01.kbs1.net:7070"
batteryLimit = 75
    [evcc.morning]
    start = 0
    end = 9
    [evcc.afternoon]
    start = 10
    end = 20


[homeassistant]
host = "hassi-01.kbs1.net:8123"
token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIxYmYwZmNlYzBiZmE0ZWIwOGZiMDk3YTMyOTU4MzJjNCIsImlhdCI6MTc0NDk2NjM5NywiZXhwIjoyMDYwMzI2Mzk3fQ.Jd_7flOWXpTfKPV0CSGs7fdkJgdagBmjdlp9FrhV9xg"
text_entityid = "input_text.evcc_lowest_price"