GET http://evcc-01:7070/api/state

###

POST http://evcc-01:7070/api/batterygridchargelimit/0.205

###
POST http://evcc-01:7070/api/auth/login

{
    "password": "15.nixu"
}

###
POST https://api.tibber.com/v1-beta/gql
Content-Type: application/json
Authorization: Bearer jFVRLY0sX9RWXqoZ40XO4f25hrYHwsaLAcb_k0sHfL0

{ "query": "{viewer {homes {currentSubscription {priceInfo {today {total startsAt }}}}}}" }



###

{ "query": "{viewer {homes {currentSubscription {priceInfo {today {total energy tax startsAt }}}}}}" }

